# Generated by Django 3.0.14 on 2023-08-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        
    ]
