# Generated by Django 4.2.5 on 2023-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bannerslide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(upload_to='bannerslides/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Banner Slide',
                'verbose_name_plural': 'Banner Slides',
                'ordering': ['order'],
            },
        ),
    ]
