# Generated by Django 4.2.5 on 2023-10-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0003_bannerslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
