# Generated by Django 4.2.5 on 2023-10-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('history', models.TextField()),
                ('height', models.FloatField()),
                ('born_date', models.DateField()),
                ('born_location', models.CharField(max_length=255)),
                ('died_date', models.DateField()),
                ('died_location', models.CharField(max_length=255)),
                ('video', models.URLField(blank=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('star_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminHome.star')),
                ('awards_won', models.PositiveIntegerField()),
                ('notable_movies', models.TextField()),
            ],
            bases=('adminHome.star',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('star_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminHome.star')),
                ('films_directed', models.PositiveIntegerField()),
                ('style_signature', models.TextField()),
            ],
            bases=('adminHome.star',),
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('star_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminHome.star')),
                ('books_published', models.PositiveIntegerField()),
                ('genres_written', models.TextField()),
            ],
            bases=('adminHome.star',),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.star')),
            ],
        ),
        migrations.CreateModel(
            name='StarImageURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.star')),
            ],
        ),
        migrations.CreateModel(
            name='StarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stars/')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.star')),
            ],
        ),
        migrations.CreateModel(
            name='Spouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_name', models.CharField(max_length=255)),
                ('marriage_date', models.DateField()),
                ('divorce_date', models.DateField(blank=True, null=True)),
                ('children_count', models.PositiveIntegerField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.star')),
            ],
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.star')),
            ],
        ),
        migrations.CreateModel(
            name='OtherWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.star')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.star')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_name', models.CharField(max_length=255)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.star')),
            ],
        ),
    ]
