# Generated by Django 4.2.5 on 2023-10-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0005_star_actor_director_writer_videos_starimageurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official_sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=100)),
                ('Official_sites', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='StarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='actor',
            name='star_ptr',
        ),
        migrations.RemoveField(
            model_name='director',
            name='star_ptr',
        ),
        migrations.DeleteModel(
            name='myuser',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='star_ptr',
        ),
        migrations.RemoveField(
            model_name='spouses',
            name='children_count',
        ),
        migrations.RemoveField(
            model_name='spouses',
            name='divorce_date',
        ),
        migrations.RemoveField(
            model_name='spouses',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='star',
            name='video',
        ),
        migrations.AddField(
            model_name='spouses',
            name='divorce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spouses',
            name='spouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_star', to='adminHome.star'),
        ),
        migrations.AddField(
            model_name='starimage',
            name='mainimage',
            field=models.BooleanField(default=False, verbose_name='Is Main'),
        ),
        migrations.AlterField(
            model_name='alternativenames',
            name='alternative_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='children',
            name='child_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_star', to='adminHome.star'),
        ),
        migrations.AlterField(
            model_name='star',
            name='died_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='died_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='height',
            field=models.FloatField(default=0, help_text='height in meters.'),
        ),
        migrations.AlterField(
            model_name='star',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
        migrations.AddField(
            model_name='official_sites',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHome.star'),
        ),
        migrations.AddField(
            model_name='star',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='stars', to='adminHome.startype'),
        ),
    ]
