# Generated by Django 4.2.5 on 2023-10-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0007_alter_star_born_date_alter_star_born_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='children',
            name='star',
        ),
        migrations.RemoveField(
            model_name='official_sites',
            name='star',
        ),
        migrations.RemoveField(
            model_name='otherworks',
            name='star',
        ),
        migrations.RemoveField(
            model_name='relatives',
            name='star',
        ),
        migrations.RemoveField(
            model_name='spouses',
            name='spouse',
        ),
        migrations.RemoveField(
            model_name='spouses',
            name='star',
        ),
        migrations.RemoveField(
            model_name='star',
            name='job',
        ),
        migrations.RemoveField(
            model_name='starimage',
            name='star',
        ),
        migrations.RemoveField(
            model_name='starimageurl',
            name='star',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='star',
        ),
        migrations.DeleteModel(
            name='AlternativeNames',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='Official_sites',
        ),
        migrations.DeleteModel(
            name='OtherWorks',
        ),
        migrations.DeleteModel(
            name='Relatives',
        ),
        migrations.DeleteModel(
            name='Spouses',
        ),
    ]
