# Generated by Django 4.2.5 on 2023-10-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_localimage_star_alter_movie_director_and_more'),
        ('adminHome', '0008_remove_children_child_name_remove_children_star_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
        migrations.DeleteModel(
            name='StarImage',
        ),
        migrations.DeleteModel(
            name='StarImageURL',
        ),
        migrations.DeleteModel(
            name='StarType',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
