# Generated by Django 4.2.5 on 2023-10-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0010_premium_premium_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
