# Generated by Django 4.2.5 on 2023-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0012_alter_premium_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='date',
        ),
        migrations.AddField(
            model_name='premium',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
