# Generated by Django 4.2.5 on 2024-01-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0017_remove_comment_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='toplike',
            field=models.IntegerField(default=0),
        ),
    ]
