# Generated by Django 4.2.5 on 2024-02-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0018_comment_toplike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default='Neutral', max_length=8),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
    ]
