# Generated by Django 4.2.5 on 2024-02-26 16:24

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminHome', '0020_gameplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplay',
            name='sessions_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameplay',
            name='play_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='gameplay',
            unique_together={('user', 'play_date')},
        ),
    ]
