# Generated by Django 4.2.5 on 2024-02-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0021_gameplay_sessions_today_alter_gameplay_play_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplay',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gameplay',
            name='play_date',
        ),
    ]
