# Generated by Django 4.2.5 on 2024-04-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0022_alter_gameplay_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium',
            old_name='imag',
            new_name='image',
        ),
    ]
