# Generated by Django 4.2.5 on 2023-10-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0007_alter_star_born_date_alter_star_born_location_and_more'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.ManyToManyField(related_name='writer_movies', to='adminHome.star'),
        ),
    ]
