# Generated by Django 4.2.5 on 2023-10-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0007_alter_star_born_date_alter_star_born_location_and_more'),
        ('movies', '0003_alter_movie_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localimage',
            old_name='is_main',
            new_name='mainstar',
        ),
        migrations.RemoveField(
            model_name='urlimage',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='video',
            name='star',
        ),
        migrations.AddField(
            model_name='localimage',
            name='mainmovie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director_movies', to='adminHome.star'),
        ),
        migrations.AddField(
            model_name='urlimage',
            name='mainmovie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urlimage',
            name='mainstar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='localimage',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_images', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='localimage',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='local_star_images', to='adminHome.star'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.ManyToManyField(related_name='written_movies', to='adminHome.star'),
        ),
        migrations.AlterField(
            model_name='urlimage',
            name='is_visible',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlimage',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_images', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='urlimage',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='url_star_images', to='adminHome.star'),
        ),
    ]
