# Generated by Django 4.2.5 on 2023-10-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0002_startype_star_active_star_born_date_and_more'),
        ('movies', '0004_rename_is_main_localimage_mainstar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localimage',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='local_star_images', to='star.star'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director_movies', to='star.star'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.ManyToManyField(related_name='written_movies', to='star.star'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star.star'),
        ),
        migrations.AlterField(
            model_name='urlimage',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='url_star_images', to='star.star'),
        ),
    ]
