# Generated by Django 4.2.5 on 2023-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.CharField(max_length=10, verbose_name='Movie Time'),
        ),
    ]
