# Generated by Django 4.2.5 on 2024-02-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_localimage_movie_alter_urlimage_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.FloatField(verbose_name='Positive Percentage')),
                ('negative', models.FloatField(verbose_name='Negative Percentage')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Movie')),
            ],
        ),
    ]
