# Generated by Django 4.2.5 on 2023-11-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0003_remove_starimageurl_star_delete_starimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spouses',
            name='divorce_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
